/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Gustavo Cavero' at '6/10/15 3:53 PM' with Gradle 2.1
 *
 * @author Gustavo Cavero, @date 6/10/15 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
